config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users, :sessions

  root 'pokers#index'

  resources :pokers do
    collection do
      put 'subscribe'
    end
  end

end

app/models/poker.rb
class Poker < ActiveRecord::Base

  belongs_to :user

  MAX_PLAYERS = 6

  def subscribed?
    user.count < MAX_PLAYERS
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :pokers

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    if current_user.nil?
      flash[:danger] = "Not authorized"
      redirect_to login_url
    end
  end
end

app/controllers/pokers_controller.rb
class PokersController < ApplicationController

  before_filter :authorize

  def index
    @unsubscribe_pokers = Poker.where("subscribe_at IS NULL")
    @subscribe_pokers   = Poker.where("subscribe_at IS NOT NULL")
  end

  def subscribe
    @pokers = Poker.where(id: params[:poker_ids])
    @pokers.update_all(subscribe_at: Time.now)
    @pokers.update_all("max_players = max_players + 1")
    redirect_to pokers_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create 
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Log out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank's for signing up!"
    else
      render "new"
    end
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
        class: "alert fade in alert-#{type} #{tag_class}"
      }.merge(options)

      close_button = content_tag(:button, raw("&times;"), type: "button", class: "close", "data-dismiss" => "alert")

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg, tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/pokers_helper.rb
module PokersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PokerGame</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
 <body>
    <%= render 'shared/navbar' %>
    <%= bootstrap_flash %>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class=".col-md-8">
          <%= yield %>
       </div>
      </div><!--/row-->
    </div> <!-- /container -->
      <footer class="footer">
        <div class="panel-footer">
          <p class="text-muted text-center">
            by <a href="https://github.com/davygora">@davygora for Diversido Mobile</a>
          </p>
        </div>
      </footer>
  </body>
</html>

app/views/pokers/index.html.erb
  <h1 class="text-center">Welcome to online Poker Game</h1>
  <h4 class="text-center">Please, choose some tables and subscribe</h4>
  <%= form_tag subscribe_pokers_path, :method => :put do %>
    <div class="row text-center">
    <% for poker in @unsubscribe_pokers do %>
      <div class="col-md-3 col-sm-6 hero-feature">
          <div class="thumbnail">
              <div class="caption">
                  <h3><%= poker.name %></h3>
                  <h4><%= poker.start_time %></h4>
                  <% if poker.max_players < 6 %>
                    <label><%= check_box_tag 'poker_ids[]', poker.id %>Select</label>
                  <% else %>
                    <h4>You can't subscribe</h4>
                    <% end %>
                  <h5><%= poker.max_players %></h5>
              </div>
          </div>
      </div>
    <% end %>
    <%= submit_tag "Subscribe" %>
  <% end %>
</div>
<h1 class="text-center">You subscribe at</h1>
<% for poker in @subscribe_pokers do %>
  <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
          <div class="caption">
              <h3><%= poker.name %></h3>
              <h4><%= poker.start_time %></h4>
          </div>
      </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default ">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" <%= link_to 'Online Poker Game', root_path %> </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><a>Hello! <%= current_user.email %></a></li>
          <li><%= link_to "Logout", logout_path %></li>
        <% else %>
          <li><%= link_to "SignUp", signup_path %></li>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<div class="container">
  <div class="row text-center pad-top ">
    <div class="col-md-12">
      <h2>Registration</h2>
      <% if @user.errors.any? %>
        <div class="alert alert-danger", role="alert">
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row  pad-top">
    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong> Register Yourself </strong>
        </div>
            <div class="panel-body">
              <%= form_for @user do |f| %>
<br/>
                <div class="form-group input-group">
                  <span class="input-group-addon">@</span>
                    <%= f.text_field :email, class: "form-control", placeholder: "Your email" %>
                </div>
                <div class="form-group input-group">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-ok-circle"  ></i></span>
                  <%= f.password_field :password, class: "form-control", placeholder: "Enter Password" %>
                </div>
                <div class="form-group input-group">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-ok-circle"  ></i></span>
                  <%= f.password_field :password, class: "form-control", placeholder: "Retype password" %>
                </div>
                <%= f.submit "Register Me", class: "btn btn-success " %>
              <hr />
                Already Registered ?
                <%= link_to "Login here", login_path %>
                <% end %>
            </div>
      </div>
    </div>
  </div>
</div>